
# Dataset's constants
DATASET_IMAGE_WIDTH = 20
DATASET_IMAGE_HEIGHT = 20
DATASET_IMAGE_CHANNEL = 1   

# Firebase's constants
ESP32_IP = "192.168.0.102"
LOW_QUAL_CAM = "cam-lo.jpg"
MD_QUAL_CAM = "cam-mid.jpg"
HIGH_QUAL_CAM = "cam-hi.jpg"
PREDICT_PORT = 8085
TRANFER_MODEL_PORT = 8086
PORT_3 = 8087 
